# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "true"
end

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do |options|
    if options[:buildNo]
      increment_build_number(xcodeproj: "Runner.xcodeproj", build_number: options[:buildNo])
    else
      puts "Build number unknown"
      sh("exit 1")
    end
    if options[:versionNo]
      increment_version_number(xcodeproj: "Runner.xcodeproj", version_number: options[:versionNo])
    else
      puts "Version number unknown"
      sh("exit 1")
    end
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
